learning_log/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include,url

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('', include('users.urls', namespace='users')),
    path('',include(('users.urls','users'),namespace='users')),
    path('',include(('learning_logs.urls','learning_logs'),namespace='learning_logs')),
    #url(r'^admin/',include(admin.site.urls)),
    #url(r'',include('learning_logs.urls',namespace='learning_logs')),

]

learning_logs/urls.py
"""
定义learning_logs的URL模式
"""
from django.contrib import admin
from django.urls import path
from django.conf.urls import include,url,re_path
from django.urls import path
from . import views
app_name = 'learning_logs'
urlpatterns = [
    #path('admin/', admin.site.urls),
    #url(r'^$',views.index,name='index'),#r'^$'这是个正则表达式，让python查找开头和末尾之间没有任何东西的URL，其他的都不是互相匹配的
    path('',views.index,name='index'),
    #re_path('^topic/$',views.topics,name='topics'),
    #path('topics/',views.topics,name='topics'),
    path('topics/', views.topics, name='topics'),
    path("topics/(?P<topic_id>\d+)/", views.topic, name='topic'),
    # 运用了正则表达式，表达式两边的括号捕获URL中的值，?P<topic_id>将匹配的值存储到topic_id中，\d+与包含在斜杠内的任何数字都匹配，不管为多少位
    # 发现URL匹配时。将调用视图函数topic,并将存储在topic_id中的值作为实参传递给他，使用topic_id的值获取相应的主题
    path('new_topic/',views.new_topic,name='new_topic'),
    path('new_entry/(?P<topic_id>\d+)/',views.new_entry,name='new_entry'),#用于添加新条目的页面
    #在用于添加新条目的页面的URL模式中，需要包含实参topic_id,因为条目必须与特定的主题相关联
    path('edit_entry/<int:entry_id>/',views.edit_entry,name='edit_entry'),#用于编辑条目的页面
]

users/urls.py
"""Defines url patterns for users."""
from django.conf.urls import url
from django.urls import path, include, re_path
from django.contrib.auth.views import LoginView
from django.contrib.auth import logout,login,authenticate
from . import views
app_name = 'users'
LoginView.template_name = 'users/login.html'
urlpatterns = [
    # Login page.
    path('users/login/', LoginView.as_view(), name='login'),
        
    # Logout page.
    path('logout/', views.logout_view, name='logout'),
    
    # Registration page. 
    path('register/', views.register, name='register'),
]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User
#from __future__ import unicode_literals
# Create your models here.
class Topic(models.Model):
    """用户学习的主题"""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    #text是由字符或文本组成的数据，并设置固定长度，date_added记录日期和时间的数据，当用户创建新主题时，将属性设置成当前日期和时间
    owner = models.ForeignKey(User,on_delete=models.CASCADE)
    def __str__(self):
        """返回模型的字符串表示"""
        return self.text
"""
为用户在学习笔记中添加的条目定义模型，每个条目都与特定主题相关联，这种关系被称为多对一关系，即多个条目可关联到同一个主题
外键是一个数据库术语，它引用了数据库中的另一条记录，下面的代码将每个条目关联到特定的主题，每个主题创建时都分配了一个键（或ID），需要数据联系时，使用键关联。
"""
class Entry(models.Model):
    """学到的有关某个主题的具体知识"""
    topic = models.ForeignKey(Topic,on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    class Meta:
        verbose_name_plural = 'entries'
    def __str__(self):
        """返回模型的字符串表示，只让条目显示text的前50个字符，所以添加了省略号"""
        return self.text[:50] + "..."

users/models.py
from django.db import models

# Create your models here.

learning_logs/forms.py
"""
创建表单的最简单方式是使用ModelForm,根据在上述定义的模型中的信息自动创建表单,最简单的ModelForm版本只含有一个内嵌的Meta类，告诉django根据哪个模型创建表单
以及在表单中含有哪些字段，根据Topic创建一个表单，以及在表单中包含text字段，labels让django不要为字段text生成标签
"""
from django import forms
from .models import Topic,Entry
class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = {'text'}
        labels = {'text':''}
"""
新类EntryForm继承了forms.ModelForm,它包含的Meta类指出了表单基于的模型以及要在表单中包含哪些字段，这里也给text指定了一个空标签
属性widgets，小部件widget是一个html表单元素，如单行文本框，多行文本区域或下拉列表，设置widgets可以覆盖django选择的默认小部件，宽度设置为80列而不是默认的40
"""
class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text':''}
        widgets = {'text':forms.Textarea(attrs={'cols':80})}

learning_logs/views.py
from django.shortcuts import render
from .models import Topic,Entry
from django.urls import reverse
from django.http import HttpResponseRedirect,Http404
from .forms import TopicForm,EntryForm
from django.contrib.auth.decorators import login_required
#django使用了装饰器@login_required限制访问，对于某些页面只允许允许已登陆的用户访问它们，装饰器（decorator）是放在函数定义前面的指令
# Create your views here.
def index(request):
    """学习笔记的主页"""
    return render(request,'learning_logs/index.html')
#加上@login_required之后，让python运行topics()的代码前先运行login_required的代码
#login_required的代码检查用户是否已经登陆，仅当用户登录时，django才运行topics的代码，如果用户未登陆，就重定向到登陆页面
@login_required
def topics(request):
    """显示所有的主题"""
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    #topics = Topic.objects.order_by('date_added') #查询数据库，请求提供Topic对象，并按属性data_added对他们进行排序
    context = {'topics':topics} #定义了一个将要发送给模板的上下文，为字典
    return render(request,'learning_logs/topics.html',context)
@login_required
def topic(request,topic_id):
    """显示单个主题及其所有的条目"""
    topic = Topic.objects.get(id=topic_id)
    # 确认请求的主题属于当前用户
    if topic.owner != request.user:
        raise Http404
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic':topic,'entries':entries}
    #这个代码称为查询，向数据库查询特定的信息
    return render(request,'learning_logs/topic.html',context)
@login_required
def new_topic(request):
    """添加新主题"""
    if request.method != 'POST':
        #未提交数据，创建一个新表单
        form = TopicForm()
    else:
        #POST提交的数据，对数据进行处理
        form = TopicForm(request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return HttpResponseRedirect(reverse('learning_logs:topics'))
    #函数reverse根据制定的URL模型确定URL，意味着django将在页面被请求时生成URL
    context = {'form':form}
    return render(request,'learning_logs/new_topic.html',context)
@login_required
def new_entry(request,topic_id):
    """在特定的主题中添加新条目"""
    topic = Topic.objects.get(id=topic_id)
    if request.method != 'POST':
        # 未提交数据，创建一个空表单
        form = EntryForm()
    else:#post提交的数据，对数据进行处理
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return HttpResponseRedirect(reverse('learning_logs:topic',args=[topic_id]))
    context = {'topic':topic,'form':form}
    return render(request,'learning_logs/new_entry.html',context)
@login_required
def edit_entry(request,entry_id):
    """编辑既有条目"""
    entry = Entry.objects.get(id=entry_id) #获取用户要修改的的条目对象，以及与该条目相关的主题
    topic = entry.topic
    if request.method != 'POST':
        # 初次请求，使用当前条目填充表单
        form = EntryForm(instance=entry)#让django创建一个表单，并使用既有条目对象中的信息填充它，用户将看到既有的数据并编辑他们
    else:
        # POST提交的数据，对数据进行处理，传递着两个实参，让django根据既有条目对象创建一个表单实例，并根据requese.POST中的相关数据进行修改
        # 然后检查表单是否有效，如果有效，就调用save,然后重新定向到显示条目所属主题的页面，用户将在其中看到其编辑的条目的新版本
        form = EntryForm(instance=entry,data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('learning_logs:topic',args=[topic.id]))
    context = {'entry':entry,'topic':topic,'form':form}
    return render(request,'learning_logs/edit_entry.html',context)

users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import UserCreationForm

def logout_view(request):
    """Log the user out."""
    logout(request)
    return HttpResponseRedirect(reverse('learning_logs:index'))

def register(request):
    """Register a new user."""
    if request.method != 'POST':
        # Display blank registration form.   
        form = UserCreationForm()
    else:
        # Process completed form.
        form = UserCreationForm(data=request.POST)
        
        if form.is_valid():
            new_user = form.save()
            # Log the user in, and then redirect to home page.
            authenticated_user = authenticate(username=new_user.username,
                password=request.POST['password1'])
            login(request, authenticated_user)
            return HttpResponseRedirect(reverse('learning_logs:index'))

    context = {'form': form}
    return render(request, 'users/register.html', context)

learning_logs/templates/learning_logs/base.html
{% load bootstrap3 %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Learning Log</title>
    {% bootstrap_css %}
    {% bootstrap_javascript %}
  </head>
  <body>
    <!-- Static navbar -->
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed"
              data-toggle="collapse" data-target="#navbar"
              aria-expanded="false" aria-controls="navbar">
          </button>
            <!--定义一个按钮，将在浏览器窗口太窄，无法水平显示整个导航栏时显示出来-->
          <a class="navbar-brand" href="{% url 'learning_logs:index' %}">Learning Log</a>
            <!--最左边显示项目名，并将其设置为到主页的链接，因为他将出现在这个项目的每个页面中-->
        </div>

        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'learning_logs:topics' %}">Topics</a></li>
          </ul>
<!--导航栏实际上使一个以<ul>打头的列表，其中每个链接都是一个列表项<li>,要添加更多的链接，可插入更多使用下述结构的行这行表示导航栏中的一个链接，从base.html复制过来的-->
          <ul class="nav navbar-nav navbar-right">
          <!--出现导航栏右边，登陆链接和注册链接通常出现在右边-->
            {% if user.is_authenticated %}
              <li><a>Hello, {{ user.username }}.</a></li>
              <li><a href="{% url 'users:logout' %}">log out</a></li>
            {% else %}
              <li><a href="{% url 'users:register' %}">register</a></li>
              <li><a href="{% url 'users:login' %}">log in</a></li>
            {% endif %}
          </ul>
        </div><!--/.nav-collapse -->

      </div>
    </nav>

    <div class="container">

      <div class="page-header">
        {% block header %}{% endblock %}
      </div>
      <div>
        {% block content %}{% endblock %}
      </div>

    </div> <!-- /container -->

  </body>
</html>
<!--
1处是一个<nav>元素，表示页面的导航链接部分，对于这个元素内的所有内容，都将根据选择器(selector),navbar\navbar-default\navbar-static-top
定义的Bootstrap样式规则来设置样式，选择器决定了特定样式将应用于页面上的哪些元素。
-->

learning_logs/templates/learning_logs/edit_entry.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>编辑条目的页面</title>
</head>
<body>
{% extends "learning_logs/base.html" %}
{% block content %}
  <p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>
  <p>Edit entry:</p>
  <form action="{% url 'learning_logs:edit_entry' entry.id %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">save changes</button>
  </form>
{% endblock content %}
</body>
</html>

learning_logs/templates/learning_logs/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Learning Log</title>

</head>
<body>
{% extends "learning_logs/base.html" %}
{% block header %}
<div class="jumbotron">
    <h1>Trcak your learning.</h1>
</div>
{% endblock header %}
{% block content %}
 <!-- <p>Learning Log helps you keep track of your learning,for any topic you're learning about.</p>
 -->
    <h2>
    <a href="{% url 'users:register' %}">Register an account</a> to make your
    own Learning Log,and list the topics you're learning about.
    </h2>
    <h2>
    Whenever you learn something new about a topic, make an entrysummarizing what you've learned.
    </h2>
{% endblock content %}
</body>
</html>

learning_logs/templates/learning_logs/new_entry.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>New Entry</title>
</head>
<body>
{% extends "learning_logs/base.html" %}

{% block content %}

  <p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>

  <p>Add a new entry:</p>
  <form action="{% url 'learning_logs:new_entry' topic.id %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name='submit'>add entry</button>
  </form>

{% endblock content %}
</body>
</html>

learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}

{% block header %}
  <h2>Add a new topic:</h2>
{% endblock header %}

{% block content %}
    
  <form action="{% url 'learning_logs:new_topic' %}" method='post'
      class="form">
      
    {% csrf_token %}
    {% bootstrap_form form %}
    
    {% buttons %}
      <button name="submit" class="btn btn-primary">add topic</button>
    {% endbuttons %}
    
  </form>
    
{% endblock content %}

learning_logs/templates/learning_logs/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

learning_logs/templates/learning_logs/topic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends "learning_logs/base.html" %}
{% block header %}
  <h2>{{ topic }}</h2>
{% endblock header %}
{% block content %}
    <p>
    <a href="{% url 'learning_logs:new_entry'  topic.id %}">
        add new entry
    </a>
    </p>
{% for entry in entries %}
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3>
          {{ entry.date_added|date:'M d, Y H:i' }}
          <small>
            <a href="{% url 'learning_logs:edit_entry' entry.id %}">
              edit entry</a>
          </small>
        </h3>
      </div>
      <div class="panel-body">
        {{ entry.text|linebreaks }}
      </div>
    </div> <!-- panel -->
  {% empty %}
    There are no entries for this topic yet.
  {% endfor %}

{% endblock content %}

</body>
</html>

learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}
{% block header %}
  <h1>Topics</h1>
{% endblock %}
{% block content %}
  <ul>
    {% for topic in topics %}
      <li>
        <h3>
          <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
        </h3>
      </li>
    {% empty %}
      <li>No topics have been added yet.</li>
    {% endfor %}
  </ul>
  <h3><a href="{% url 'learning_logs:new_topic' %}">Add a new topic:</a></h3>
{% endblock content %}

users/templates/users/login.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}
{% block header %}
    <!--header块，描述了 这个页面-->
<h2>Log in to your account.</h2>
{% endblock header %}
{% block content %}
<form method="post" action="{% url 'users:login'%}" class="form">
{% csrf_token %}
{% bootstrap_form form %}
{% buttons %}
<button name="submit" class="btn btn-primary">log in</button>
{% endbuttons %}
<input type="hidden" name="next"
      value="{% url 'learning_logs:index' %}" />
</form>
    
{% endblock content %}

users/templates/users/register.html
{% extends "learning_logs/base.html" %}

{% block content %}

  <form method="post" action="{% url 'users:register' %}">
    {% csrf_token %}
    {{ form.as_p }}
        
    <button name="submit">register</button>
    <input type="hidden" name="next"
      value="{% url 'learning_logs:index' %}" />
  </form>

{% endblock content %}